line_length: 150
disabled_rules:
  - operator_whitespace
  - line_length
excluded:
  - Carthage
  - LoopKit/Generated
  - Loop/Generated
custom_rules:
  use_color_literal:
    included: ".*\\.swift"
    name: Use color literal from swiftgen
    match_kinds:
      - identifier
    message: "Don't use `UIColor(named:)`, use generated literal instead"
    severity: warning
    regex: "UIColor\\(named:"
  use_new_logging_framework:
    included: ".*\\.swift"
    name: "Use os.log framework because it's great"
    regex: "(NSLog|print)\\("
    severity: warning
    match_kinds:
      - identifier
identifier_name:
  excluded:
    - id
type_name:
  excluded:
    - ID
large_tuple:
  warning: 3

